# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelPic', models.ImageField(default='pic_folder/None/empty.jpg', upload_to='pic_folder/')),
            ],
        ),
    ]
