# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='modelPic',
        ),
        migrations.AddField(
            model_name='pic',
            name='UploadedFile',
            field=models.FileField(blank=True, default='DEFAULT VALUE', null=True, upload_to='pic_folder/'),
        ),
    ]
