# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grind', '0002_auto_20170612_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_cloud',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point_cloud',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point_cloud',
            name='z',
            field=models.IntegerField(default=0),
        ),
    ]
