# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grind', '0003_auto_20170612_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_cloud',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='point_cloud',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='point_cloud',
            name='z',
            field=models.FloatField(default=0),
        ),
    ]
