# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grind', '0005_point_cloud_xyzpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point_cloud',
            name='xyzpoint',
        ),
    ]
