# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_cachefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_cloud',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
