# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0003_point_cloud_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_cloud',
            name='imp',
            field=models.IntegerField(default=0),
        ),
    ]
