# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0007_thisgeom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThisGeom',
        ),
    ]
