# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 19:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0008_delete_thisgeom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_cloud',
            name='xypoint',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
