# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadedFile', models.FileField(blank=True, default='DEFAULT VALUE', null=True, upload_to='pic_folder/')),
            ],
        ),
    ]
