# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pic',
            name='UploadedFile',
            field=models.FileField(blank=True, default='DEFAULT VALUE', null=True, upload_to=''),
        ),
    ]
