# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testB', '0002_auto_20170510_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
