# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testB', '0003_namecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=200, verbose_name=b'Name')),
                ('pict', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'Picture')),
            ],
        ),
    ]
