# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.FileField(blank=True, default='DEFAULT VALUE', null=True, upload_to='pc_cache/')),
            ],
        ),
    ]
