# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 13:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.FileField(blank=True, default='DEFAULT VALUE', null=True, upload_to='pc_cache/')),
            ],
        ),
        migrations.CreateModel(
            name='Point_Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('imp', models.FloatField(default=0)),
                ('xypoint', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=28992)),
            ],
        ),
    ]
