# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0004_point_cloud_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_cloud',
            name='imp',
            field=models.FloatField(default=0),
        ),
    ]
