# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0005_auto_20170531_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_cloud',
            name='xypoint',
            field=models.TextField(null=True),
        ),
    ]
