# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 18:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0011_point_cloud_xypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_cloud',
            name='xypoint',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=28992),
        ),
    ]
